# This is a basic workflow to help you get started with Actions

name: Test & Benchmark

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: '1.2.0'

    - name: Test project
      run: nimble test
    
    - name: Run benchmarks
      run: nimble bench
